### ISSUE TITLE
Game Crashes Whenever Entering A Battle Scene

### ISSUE THREAD

**Issue by Nadezzs** [suriyun-production/turnbase-rpg-docs#246] opened 2023-04-19 03:58 UTC
As the title displays; "Game Crashes Whenever Entering A Battle Scene". I'm not missing any files, whether it be in a build or the unity editor; and upon entering the 'BattleScene', the game crashes! No log/or error is displayed.

**Comment by insthync** [comment] 2023-04-19 04:07
Which Unity version?

**Comment by insthync** [comment] 2023-04-19 04:08
May you give me your AnyDesk address? I want to try it, if you can, then send it to my email: ittipon.bay@gmail.com

**Comment by Nadezzs** [comment] 2023-04-19 04:51
Unity Version Is: 2021.3.4f1

**Comment by Nadezzs** [comment] 2023-04-19 04:52
I don't have AnyDesk since it get's blocked by my AntiVirus, can I send you a screenshot/and or video of it?

**Comment by insthync** [comment] 2023-04-19 05:14
Yes

**Comment by Nadezzs** [comment] 2023-04-19 05:28
Sent you an email!

**Comment by insthync** [comment] 2023-04-19 06:58
Try replace `GameInstance.cs` with these codes

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.SceneManagement;
#if ENABLE_PURCHASING && UNITY_PURCHASING && (UNITY_IOS || UNITY_ANDROID)
using UnityEngine.Purchasing;
#endif

#if ENABLE_PURCHASING && UNITY_PURCHASING && (UNITY_IOS || UNITY_ANDROID)
public partial class GameInstance : MonoBehaviour, IStoreListener
#else
public partial class GameInstance : MonoBehaviour
#endif
{
    public enum LoadAllPlayerDataState
    {
        GoToManageScene,
        GoToBattleScene,
    }
    public GameDatabase gameDatabase;
    public BaseGameplayRule gameplayRule;
    public UIMessageDialog messageDialog;
    public UIMessageDialog confirmDialog;
    public UIInputDialog inputDialog;
    public UIItemList rewardItemsDialog;
    public GameObject loadingObject;
    public string loginScene;
    public string manageScene;
    public string battleScene;
    public LoadSceneEvent onLoadSceneStart;
    public LoadSceneEvent onLoadSceneProgress;
    public LoadSceneEvent onLoadSceneFinish;
    public bool isRememberLogin = true;

    public static GameInstance Singleton { get; private set; }
    public static GameDatabase GameDatabase { get; private set; }
    public static BaseGameplayRule GameplayRule { get; private set; }
    public static BaseGameService GameService { get; private set; }
    public static readonly List<string> AvailableLootBoxes = new List<string>();
    public static readonly List<string> AvailableFortuneWheels = new List<string>();
    public static readonly List<string> AvailableIapPackages = new List<string>();
    public static readonly List<string> AvailableInGamePackages = new List<string>();
    public static readonly List<string> AvailableStages = new List<string>();

    private readonly Queue<UIMessageDialog.Data> _messageDialogData = new Queue<UIMessageDialog.Data>();
    private LoadAllPlayerDataState _loadAllPlayerDataState;
    private static bool _isPlayerAuthListLoaded;
    private static bool _isPlayerCurrencyListLoaded;
    private static bool _isPlayerFormationListLoaded;
    private static bool _isPlayerItemListLoaded;
    private static bool _isPlayerStaminaListLoaded;
    private static bool _isPlayerUnlockItemListLoaded;
    private static bool _isPlayerClearStageListLoaded;
    private static bool _isAvailableLootBoxListLoaded;
    private static bool _isAvailableFortuneWheelListLoaded;
    private static bool _isAvailableIapPackageListLoaded;
    private static bool _isAvailableInGamePackageListLoaded;
    private static bool _isAvailableStageListLoaded;
    private static int _countLoading = 0;
    private static AsyncOperation _loadSceneAsyncOperation;

    private void Awake()
    {
        if (Singleton != null)
        {
            Destroy(gameObject);
            return;
        }
        Singleton = this;
        DontDestroyOnLoad(gameObject);

        SetupGameDatabase();
        SetupGameplayRule();
        SetupGameService();

        HideMessageDialog();
        HideInputDialog();
        HideRewardItemsDialog();
        HideLoading();
        LoadLoginScene();
    }

    public void SetupGameDatabase()
    {
        GameDatabase = gameDatabase;
        if (GameDatabase == null)
            Debug.LogError("`Game Database` has not been set");
        else
            GameDatabase.Setup();
    }

    public void SetupGameplayRule()
    {
        GameplayRule = gameplayRule;
        if (GameplayRule == null)
            GameplayRule = ScriptableObject.CreateInstance<BaseGameplayRule>();
    }

    public void SetupGameService()
    {
        GameService = GetComponent<BaseGameService>();
        if (GameService == null)
            Debug.LogError("`Game Service` component has not been attacted");
        GameService.onServiceStart.RemoveListener(OnGameServiceStart);
        GameService.onServiceStart.AddListener(OnGameServiceStart);
        GameService.onServiceFinish.RemoveListener(OnGameServiceFinish);
        GameService.onServiceFinish.AddListener(OnGameServiceFinish);
    }

    private void OnGameServiceStart()
    {
        ShowLoading();
    }

    private void OnGameServiceFinish()
    {
        HideLoading();
    }

    public void OnGameServiceError(string error, UnityAction errorAction)
    {
        Debug.LogError("OnGameServiceError: " + error);
        _messageDialogData.Enqueue(new UIMessageDialog.Data(LanguageManager.GetText(GameText.TITLE_ERROR_DIALOG), LanguageManager.GetText(error), errorAction));
        ShowError();
    }

    public void OnGameServiceError(string error)
    {
        OnGameServiceError(error, null);
    }

    public void OnGameServiceLogin(PlayerResult result)
    {
        if (!result.Success)
            return;

        var player = result.player;
        Player.CurrentPlayer = player;
        if (isRememberLogin)
            GameService.SetPrefsLogin(player.Id, player.LoginToken);

        if (string.IsNullOrEmpty(player.ProfileName) || string.IsNullOrEmpty(player.ProfileName.Trim()))
            SetProfileName();
        else
            GetAllPlayerData(LoadAllPlayerDataState.GoToManageScene);
    }

    public void OnGameServiceLogout()
    {
        _isPlayerAuthListLoaded = false;
        _isPlayerCurrencyListLoaded = false;
        _isPlayerFormationListLoaded = false;
        _isPlayerItemListLoaded = false;
        _isPlayerStaminaListLoaded = false;
        _isPlayerUnlockItemListLoaded = false;
        _isPlayerClearStageListLoaded = false;
        _isAvailableLootBoxListLoaded = false;
        _isAvailableFortuneWheelListLoaded = false;
        _isAvailableIapPackageListLoaded = false;
        _isAvailableInGamePackageListLoaded = false;
        LoadLoginScene();
    }

    public void OnGameServiceEarnAchievementResult(EarnAchievementResult result)
    {
        if (!result.Success)
            return;

        Player.SetData(result.player);
        PlayerCurrency.SetDataRange(result.updateCurrencies);
        PlayerItem.SetDataRange(result.createItems);
        PlayerItem.SetDataRange(result.updateItems);
        PlayerItem.RemoveDataRange(result.deleteItemIds);
    }

    public void OnGameServiceItemResult(ItemResult result)
    {
        if (!result.Success)
            return;

        PlayerCurrency.SetDataRange(result.updateCurrencies);
        PlayerItem.SetDataRange(result.createItems);
        PlayerItem.SetDataRange(result.updateItems);
        PlayerItem.RemoveDataRange(result.deleteItemIds);
    }

    public void OnGameServiceStartStageResult(StartStageResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetData(result.stamina);
    }

    public void OnGameServiceFinishStageResult(FinishStageResult result)
    {
        if (!result.Success)
            return;

        Player.SetData(result.player);
        PlayerCurrency.SetDataRange(result.updateCurrencies);
        PlayerItem.SetDataRange(result.createItems);
        PlayerItem.SetDataRange(result.updateItems);
        PlayerItem.RemoveDataRange(result.deleteItemIds);
        PlayerClearStage.SetData(result.clearStage);
    }

    public void OnGameServiceStartDuelResult(StartDuelResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetData(result.stamina);
        PlayerItem.SetDataRange(result.opponentCharacters);
        PlayerItem.SetDataRange(result.opponentEquipments);
    }

    public void OnGameServiceFinishDuelResult(FinishDuelResult result)
    {
        if (!result.Success)
            return;

        Player.SetData(result.player);
        PlayerCurrency.SetDataRange(result.updateCurrencies);
        PlayerItem.SetDataRange(result.createItems);
        PlayerItem.SetDataRange(result.updateItems);
        PlayerItem.RemoveDataRange(result.deleteItemIds);
    }

    public void OnGameServiceStartRaidBossBattleResult(StartRaidBossBattleResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetData(result.stamina);
    }

    public void OnGameServiceStartClanBossBattleResult(StartClanBossBattleResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetData(result.stamina);
    }

    public void OnGameServiceSetProfileNameResult(PlayerResult result)
    {
        if (!result.Success)
            return;

        var currentPlayer = Player.CurrentPlayer;
        if (currentPlayer != null)
            currentPlayer.ProfileName = result.player.ProfileName;
    }

    public void OnGameServiceAchievementListResult(AchievementListResult result)
    {
        if (!result.Success)
            return;

        PlayerAchievement.SetDataRange(result.list);
    }

    public void OnGameServiceAuthListResult(AuthListResult result)
    {
        if (!result.Success)
            return;

        PlayerAuth.SetDataRange(result.list);
    }

    public void OnGameServiceCurrencyListResult(CurrencyListResult result)
    {
        if (!result.Success)
            return;

        PlayerCurrency.SetDataRange(result.list);
    }

    public void OnGameServiceFormationListResult(FormationListResult result)
    {
        if (!result.Success)
            return;

        PlayerFormation.SetDataRange(result.list);
    }

    public void OnGameServiceItemListResult(ItemListResult result)
    {
        if (!result.Success)
            return;

        PlayerItem.SetDataRange(result.list);
    }

    public void OnGameServiceStaminaListResult(StaminaListResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetDataRange(result.list);
    }

    public void OnGameServiceUnlockItemListResult(UnlockItemListResult result)
    {
        if (!result.Success)
            return;

        PlayerUnlockItem.SetDataRange(result.list);
    }

    public void OnGameServiceClearStageListResult(ClearStageListResult result)
    {
        if (!result.Success)
            return;

        PlayerClearStage.SetDataRange(result.list);
    }

    public void OnGameServiceAvailableLootBoxListResult(AvailableLootBoxListResult result)
    {
        if (!result.Success)
            return;

        AvailableLootBoxes.Clear();
        AvailableLootBoxes.AddRange(result.list);
    }

    public void OnGameServiceAvailableFortuneWheelListResult(AvailableFortuneWheelListResult result)
    {
        if (!result.Success)
            return;

        AvailableFortuneWheels.Clear();
        AvailableFortuneWheels.AddRange(result.list);
    }

    public void OnGameServiceAvailableIapPackageListResult(AvailableIapPackageListResult result)
    {
        if (!result.Success)
            return;

        AvailableIapPackages.Clear();
        AvailableIapPackages.AddRange(result.list);
    }

    public void OnGameServiceAvailableInGamePackageListResult(AvailableInGamePackageListResult result)
    {
        if (!result.Success)
            return;

        AvailableInGamePackages.Clear();
        AvailableInGamePackages.AddRange(result.list);
    }

    public void OnGameServiceAvailableStageListResult(AvailableStageListResult result)
    {
        if (!result.Success)
            return;

        AvailableStages.Clear();
        AvailableStages.AddRange(result.list);
    }

    public void OnGameServiceCreateClanResult(CreateClanResult result)
    {
        if (!result.Success)
            return;

        PlayerCurrency.SetDataRange(result.updateCurrencies);
    }

    public void OnGameServiceRefillStaminaResult(RefillStaminaResult result)
    {
        if (!result.Success)
            return;

        PlayerStamina.SetData(result.stamina);
        PlayerCurrency.SetData(result.currency);
    }

    public void OnGameServiceGetFormationCharactersAndEquipments(FormationCharactersAndEquipmentsResult result)
    {
        if (!result.Success)
            return;

        PlayerItem.SetDataRange(result.characters);
        PlayerItem.SetDataRange(result.equipments);
    }

    #region Current Player Data Validation
    /// <summary>
    /// Set profile name first time, when it's not already set.
    /// </summary>
    private void SetProfileName()
    {
        ShowProfileNameInputDialog(OnSetProfileNameSuccess, (error) => OnGameServiceError(error, SetProfileName));
    }

    private void OnSetProfileNameSuccess(PlayerResult result)
    {
        OnGameServiceSetProfileNameResult(result);
        GetAllPlayerData(LoadAllPlayerDataState.GoToManageScene);
    }

    /// <summary>
    /// Get all current player data after login
    /// </summary>
    public void GetAllPlayerData(LoadAllPlayerDataState loadAllPlayerDataState)
    {
        this._loadAllPlayerDataState = loadAllPlayerDataState;
        GetAuthList();
        GetCurrencyList();
        GetFormationList();
        GetItemList();
        GetStaminaList();
        GetUnlockItemList();
        GetClearStageList();
        GetAvailableLootBoxList();
        GetAvailableFortuneWheelList();
        GetAvailableIAPPackageList();
        GetAvailableInGamePackageList();
        GetAvailableStageList();
    }

    /// <summary>
    /// Get authentication list for current player
    /// </summary>
    private void GetAuthList()
    {
        _isPlayerAuthListLoaded = false;
        GameService.GetAuthList(OnGetAuthListSuccess, (error) => OnGameServiceError(error, GetAuthList));
    }

    private void OnGetAuthListSuccess(AuthListResult result)
    {
        OnGameServiceAuthListResult(result);
        _isPlayerAuthListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get currency list for current player
    /// </summary>
    private void GetCurrencyList()
    {
        _isPlayerCurrencyListLoaded = false;
        GameService.GetCurrencyList(OnGetCurrencyListSuccess, (error) => OnGameServiceError(error, GetCurrencyList));
    }

    private void OnGetCurrencyListSuccess(CurrencyListResult result)
    {
        OnGameServiceCurrencyListResult(result);
        _isPlayerCurrencyListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get formation list for current player
    /// </summary>
    private void GetFormationList()
    {
        _isPlayerFormationListLoaded = false;
        GameService.GetFormationList(OnGetFormationListSuccess, (error) => OnGameServiceError(error, GetFormationList));
    }

    private void OnGetFormationListSuccess(FormationListResult result)
    {
        OnGameServiceFormationListResult(result);
        _isPlayerFormationListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get item list for current player
    /// </summary>
    private void GetItemList()
    {
        _isPlayerItemListLoaded = false;
        GameService.GetItemList(OnGetItemListSuccess, (error) => OnGameServiceError(error, GetItemList));
    }

    private void OnGetItemListSuccess(ItemListResult result)
    {
        OnGameServiceItemListResult(result);
        _isPlayerItemListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get stamina list for current player
    /// </summary>
    private void GetStaminaList()
    {
        _isPlayerStaminaListLoaded = false;
        GameService.GetStaminaList(OnGetStaminaListSuccess, (error) => OnGameServiceError(error, GetStaminaList));
    }

    private void OnGetStaminaListSuccess(StaminaListResult result)
    {
        OnGameServiceStaminaListResult(result);
        _isPlayerStaminaListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get unlock item list for current player
    /// </summary>
    private void GetUnlockItemList()
    {
        _isPlayerUnlockItemListLoaded = false;
        GameService.GetUnlockItemList(OnGetUnlockItemListSuccess, (error) => OnGameServiceError(error, GetUnlockItemList));
    }

    private void OnGetUnlockItemListSuccess(UnlockItemListResult result)
    {
        OnGameServiceUnlockItemListResult(result);
        _isPlayerUnlockItemListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get clear stage list for current player
    /// </summary>
    private void GetClearStageList()
    {
        _isPlayerClearStageListLoaded = false;
        GameService.GetClearStageList(OnGetClearStageListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetClearStageListSuccess(ClearStageListResult result)
    {
        OnGameServiceClearStageListResult(result);
        _isPlayerClearStageListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get list of available to open loot boxes
    /// </summary>
    private void GetAvailableLootBoxList()
    {
        _isAvailableLootBoxListLoaded = false;
        GameService.GetAvailableLootBoxList(OnGetAvailableLootBoxListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetAvailableLootBoxListSuccess(AvailableLootBoxListResult result)
    {
        OnGameServiceAvailableLootBoxListResult(result);
        _isAvailableLootBoxListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get list of available to fortune wheels
    /// </summary>
    private void GetAvailableFortuneWheelList()
    {
        _isAvailableFortuneWheelListLoaded = false;
        GameService.GetAvailableFortuneWheelList(OnGetAvailableFortuneWheelListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetAvailableFortuneWheelListSuccess(AvailableFortuneWheelListResult result)
    {
        OnGameServiceAvailableFortuneWheelListResult(result);
        _isAvailableFortuneWheelListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get list of available to open iap packages
    /// </summary>
    private void GetAvailableIAPPackageList()
    {
        _isAvailableIapPackageListLoaded = false;
        GameService.GetAvailableIapPackageList(OnGetAvailableIAPPackageListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetAvailableIAPPackageListSuccess(AvailableIapPackageListResult result)
    {
        OnGameServiceAvailableIapPackageListResult(result);
        _isAvailableIapPackageListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get list of available to open in-game packages
    /// </summary>
    private void GetAvailableInGamePackageList()
    {
        _isAvailableInGamePackageListLoaded = false;
        GameService.GetAvailableInGamePackageList(OnGetAvailableInGamePackageListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetAvailableInGamePackageListSuccess(AvailableInGamePackageListResult result)
    {
        OnGameServiceAvailableInGamePackageListResult(result);
        _isAvailableInGamePackageListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// Get list of available to enter stages
    /// </summary>
    private void GetAvailableStageList()
    {
        _isAvailableStageListLoaded = false;
        GameService.GetAvailableStageList(OnGetAvailableStageListSuccess, (error) => OnGameServiceError(error, GetClearStageList));
    }

    private void OnGetAvailableStageListSuccess(AvailableStageListResult result)
    {
        OnGameServiceAvailableStageListResult(result);
        _isAvailableStageListLoaded = true;
        ValidatePlayerData();
    }

    /// <summary>
    /// When receive all current player data, load manage scene
    /// </summary>
    private void ValidatePlayerData()
    {
        if (_isPlayerAuthListLoaded &&
            _isPlayerCurrencyListLoaded &&
            _isPlayerFormationListLoaded &&
            _isPlayerItemListLoaded &&
            _isPlayerStaminaListLoaded &&
            _isPlayerUnlockItemListLoaded &&
            _isPlayerClearStageListLoaded &&
            _isAvailableLootBoxListLoaded &&
            _isAvailableFortuneWheelListLoaded &&
            _isAvailableIapPackageListLoaded &&
            _isAvailableInGamePackageListLoaded &&
            _isAvailableStageListLoaded)
        {
            // Setup purchasing when all data loaded
            SetupPurchasing();
            switch (_loadAllPlayerDataState)
            {
                case LoadAllPlayerDataState.GoToManageScene:
                    LoadManageScene();
                    break;
                case LoadAllPlayerDataState.GoToBattleScene:
                    LoadBattleScene();
                    break;
            }
        }
    }
    #endregion

    #region Error/Warning/Loading Handler
    private void ShowError()
    {
        if (_messageDialogData.Count > 0)
        {
            var data = _messageDialogData.Dequeue();
            ShowMessageDialog(data.title, data.content, () =>
            {
                ShowError();
                if (data.actionYes != null)
                    data.actionYes.Invoke();
            }, data.actionNo, data.actionCancel);
        }
    }

    public void ShowMessageDialog(string title,
        string content,
        UnityAction actionYes = null,
        UnityAction actionNo = null,
        UnityAction actionCancel = null)
    {
        if (messageDialog == null)
        {
            Debug.LogWarning("`Message Dialog` has not been set");
            if (actionYes != null)
                actionYes.Invoke();
            return;
        }
        if (!messageDialog.IsVisible())
        {
            messageDialog.Title = title;
            messageDialog.Content = content;
            messageDialog.actionYes = actionYes;
            messageDialog.actionNo = actionNo;
            messageDialog.actionCancel = actionCancel;
            messageDialog.Show();
        }
    }

    public void HideMessageDialog()
    {
        if (messageDialog == null)
        {
            Debug.LogWarning("`Message Dialog` has not been set");
            return;
        }
        messageDialog.Hide();
    }

    public void ShowConfirmDialog(string title,
        string content,
        UnityAction actionYes = null,
        UnityAction actionNo = null,
        UnityAction actionCancel = null)
    {
        if (confirmDialog == null)
        {
            Debug.LogWarning("`Confirm Dialog` has not been set");
            if (actionYes != null)
                actionYes.Invoke();
            return;
        }
        if (!confirmDialog.IsVisible())
        {
            confirmDialog.Title = title;
            confirmDialog.Content = content;
            confirmDialog.actionYes = actionYes;
            confirmDialog.actionNo = actionNo;
            confirmDialog.actionCancel = actionCancel;
            confirmDialog.Show();
        }
    }

    public void HideConfirmDialog()
    {
        if (confirmDialog == null)
        {
            Debug.LogWarning("`Confirm Dialog` has not been set");
            return;
        }
        confirmDialog.Hide();
    }

    private void ShowProfileNameInputDialog(UnityAction<PlayerResult> onSuccess, UnityAction<string> onError)
    {
        if (inputDialog == null)
        {
            Debug.LogWarning("`Input Dialog` has not been set");
            return;
        }
        ShowInputDialog(LanguageManager.GetText(GameText.TITLE_PROFILE_NAME_DIALOG),
            LanguageManager.GetText(GameText.CONTENT_PROFILE_NAME_DIALOG),
            () =>
            {
                var input = inputDialog.InputContent;
                GameService.SetProfileName(input, onSuccess, onError);
            });
        inputDialog.InputPlaceHolder = LanguageManager.GetText(GameText.PLACE_HOLDER_PROFILE_NAME);
    }

    public void ShowInputDialog(string title,
        string content,
        UnityAction actionYes = null,
        UnityAction actionNo = null,
        UnityAction actionCancel = null)
    {
        if (inputDialog == null)
        {
            Debug.LogWarning("`Input Dialog` has not been set");
            return;
        }
        inputDialog.SetInputPropertiesToDefault();
        if (!inputDialog.IsVisible())
        {
            inputDialog.Title = title;
            inputDialog.Content = content;
            inputDialog.actionYes = actionYes;
            inputDialog.actionNo = actionNo;
            inputDialog.actionCancel = actionCancel;
            inputDialog.Show();
        }
    }

    public void ShowInputDialog(string title,
        string content,
        UnityAction<int> onConfirmInteger,
        int? minAmount = null,
        int? maxAmount = null,
        int defaultAmount = 0)
    {
        if (inputDialog == null)
        {
            Debug.LogWarning("`Input Dialog` has not been set");
            return;
        }
        inputDialog.SetInputPropertiesToDefault();
        if (!inputDialog.IsVisible())
        {
            inputDialog.Show(title, content, onConfirmInteger, minAmount, maxAmount, defaultAmount);
            inputDialog.actionYes = null;
            inputDialog.actionNo = null;
            inputDialog.actionCancel = null;
        }
    }

    public void ShowInputDialog(string title,
        string content,
        UnityAction<float> onConfirmDecimal,
        int? minAmount = null,
        int? maxAmount = null,
        int defaultAmount = 0)
    {
        if (inputDialog == null)
        {
            Debug.LogWarning("`Input Dialog` has not been set");
            return;
        }
        inputDialog.SetInputPropertiesToDefault();
        if (!inputDialog.IsVisible())
        {
            inputDialog.Show(title, content, onConfirmDecimal, minAmount, maxAmount, defaultAmount);
            inputDialog.actionYes = null;
            inputDialog.actionNo = null;
            inputDialog.actionCancel = null;
        }
    }

    public void HideInputDialog()
    {
        if (inputDialog == null)
        {
            Debug.LogWarning("`Input Dialog` has not been set");
            return;
        }
        inputDialog.Hide();
    }

    public void ShowRewardItemsDialog(List<PlayerItem> items)
    {
        if (rewardItemsDialog == null)
        {
            Debug.LogWarning("`Reward Items Dialog` has not been set");
            return;
        }
        rewardItemsDialog.SetListItems(items);
        rewardItemsDialog.Show();
    }

    public void HideRewardItemsDialog()
    {
        if (rewardItemsDialog == null)
        {
            Debug.LogWarning("`Reward Items Dialog` has not been set");
            return;
        }
        rewardItemsDialog.Hide();
    }

    public void WarnNotEnoughSoftCurrency()
    {
        OnGameServiceError(GameServiceErrorCode.NOT_ENOUGH_SOFT_CURRENCY);
    }

    public void WarnNotEnoughHardCurrency()
    {
        OnGameServiceError(GameServiceErrorCode.NOT_ENOUGH_HARD_CURRENCY);
    }

    public void WarnNotEnoughStageStamina()
    {
        OnGameServiceError(GameServiceErrorCode.NOT_ENOUGH_STAGE_STAMINA);
    }

    public void WarnNotEnoughArenaStamina()
    {
        OnGameServiceError(GameServiceErrorCode.NOT_ENOUGH_ARENA_STAMINA);
    }

    public void ShowLoading()
    {
        if (loadingObject == null)
        {
            Debug.LogWarning("`Loading Object` has not been set");
            return;
        }
        ++_countLoading;
        if (_countLoading > 0)
            loadingObject.SetActive(true);
    }

    public void HideLoading()
    {
        if (loadingObject == null)
        {
            Debug.LogWarning("`Loading Object` has not been set");
            return;
        }
        --_countLoading;
        if (_countLoading <= 0)
        {
            loadingObject.SetActive(false);
            _countLoading = 0;
        }
    }
    #endregion

    #region Simplified Scene Loading Functions
    public void LoadLoginScene(bool loadIfNotLoaded = false)
    {
        LoadSceneIfNotLoaded(loginScene, loadIfNotLoaded);
    }

    public void LoadManageScene(bool loadIfNotLoaded = false)
    {
        LoadSceneIfNotLoaded(manageScene, loadIfNotLoaded);
    }

    public void LoadBattleScene(bool loadIfNotLoaded = false)
    {
        LoadSceneIfNotLoaded(battleScene, loadIfNotLoaded);
    }

    public void LoadSceneIfNotLoaded(string sceneName, bool loadIfNotLoaded = false)
    {
        if (SceneManager.GetActiveScene().name != sceneName || !loadIfNotLoaded)
            StartCoroutine(LoadSceneRoutine(sceneName));
    }

    IEnumerator LoadSceneRoutine(string sceneName)
    {
        if (_loadSceneAsyncOperation != null)
            yield break;
        _loadSceneAsyncOperation = SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Single);
        if (onLoadSceneStart != null)
            onLoadSceneStart.Invoke(sceneName, _loadSceneAsyncOperation.progress);
        while (!_loadSceneAsyncOperation.isDone)
        {
            if (onLoadSceneProgress != null)
                onLoadSceneProgress.Invoke(sceneName, _loadSceneAsyncOperation.progress);
            yield return null;
        }
        if (onLoadSceneFinish != null)
            onLoadSceneFinish.Invoke(sceneName, _loadSceneAsyncOperation.progress);
        _loadSceneAsyncOperation = null;
    }
    #endregion
}

```

**Comment by Nadezzs** [comment] 2023-04-19 07:20
Sadly nothing changed, it still crashes.. Just tested it in the editor, it makes my computer extremely laggy, and crashes...

**Comment by insthync** [comment] 2023-04-19 08:35
I still can't reproduce the bug yet, that is why I won't to try on your device

**Comment by Nadezzs** [comment] 2023-04-19 08:59
I'm going to try the game on Unity v2020, I'll keep you updated!

**Comment by insthync** [comment] 2023-04-19 10:22
I already tried 2021.3.22 and has no problems

**Comment by Nadezzs** [comment] 2023-04-19 10:32
Okay, is there any way I can share you my screen(do you have discord)?

**Comment by insthync** [comment] 2023-04-19 10:37
I want to find the cause of the issues by myself. What do I have to do while sharing screen? tell you to click those click that, type those, type that, it sounds inconvenient, isn't it?

**Comment by Nadezzs** [comment] 2023-04-19 10:52
True; I can give you a short overview of 'how' this bug occurred. 
1. Open a brand new unity project with version: 2021.3.4f1;
2. Import the template;
3. Setup php web services; but as there was bugs I fixed the server integration; (this step is irrelevant, as I tested it before this step and still didn't work);
4. Open the demo and login, then open the battle scene via UI;
5. Game Crashes.
No log is given, as it instantly crashes after 2 seconds of waiting.

**Comment by Nadezzs** [comment] 2023-04-19 11:18
![image](https://user-images.githubusercontent.com/115464666/233058837-5339d9b9-d77a-4f2c-a67c-db53f87bcf64.png)
Finally got it to load, but now the scene is just black, check the image to see the console!

**Comment by insthync** [comment] 2023-04-19 11:23
Click one of the error message, I want to see what is happening

**Comment by Nadezzs** [comment] 2023-04-19 11:24
![image](https://user-images.githubusercontent.com/115464666/233060412-e16aa87d-44c4-45e0-bcdf-75ce6be0f593.png)

**Comment by insthync** [comment] 2023-04-19 11:25
Scroll down or copy full messages

**Comment by Nadezzs** [comment] 2023-04-19 11:26
And also this one; 
![image](https://user-images.githubusercontent.com/115464666/233060769-461b8e83-6856-42fd-9964-940c36fd0a26.png)

**Comment by Nadezzs** [comment] 2023-04-19 11:26
Full messages:
1. ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
EnvironmentManager.Update () (at Assets/Turnbase/Scripts/Environment/EnvironmentManager.cs:41)

2. NullReferenceException: Object reference not set to an instance of an object
FollowCamera.LateUpdate () (at Assets/CameraAndInput/Scripts/Camera/FollowCamera.cs:92)
(Accidentally closed the issue)

**Comment by insthync** [comment] 2023-04-19 11:28
Okay, I want to see your stage data

**Comment by Nadezzs** [comment] 2023-04-19 11:29
> Okay, I want to see your stage data

What do you mean?(+ How do I access it)?

**Comment by insthync** [comment] 2023-04-19 11:30
I guess that you didn't setup the environment in stage data?

![Screenshot_449](https://user-images.githubusercontent.com/2697550/233061679-768a5360-356f-4837-9bdd-dd288ca05225.png)

![Screenshot_450](https://user-images.githubusercontent.com/2697550/233061705-05574df2-e419-451b-8a57-cc77b18865fd.png)

**Comment by insthync** [comment] 2023-04-19 11:31
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/009-environment-data
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/010-stage

**Comment by Nadezzs** [comment] 2023-04-19 11:34
I'm assuming I have? 
![image](https://user-images.githubusercontent.com/115464666/233062444-781bfe80-6b93-4242-be1f-adc07456edd8.png)
![image](https://user-images.githubusercontent.com/115464666/233062703-703d1704-7fb6-4d0a-8748-6cde23e9cd24.png)

**Comment by insthync** [comment] 2023-04-19 11:43
Don't know then, that is what the log is telling. If I can try it on your device it can be done in 10 minutes.

**Comment by Nadezzs** [comment] 2023-04-19 11:49
Is Environment Manager right? Because the error is pointing towards it. Here's an image; (accidentally closed issue again)
![image](https://user-images.githubusercontent.com/115464666/233065901-25bacfde-2e1e-4e41-8202-6bc0e38dbe6d.png)

**Comment by insthync** [comment] 2023-04-20 15:59
Yes, I already saw it, and it is not helpful.

I will close this because I saw only you having this issue.

**Comment by insthync** [comment] 2023-04-20 16:00
If you are ready to let me take a look or can find anyone who have the same problem, then tell me.

**Closed as not planned by insthync** 2023-04-20 15:59 UTC
